---
logging:
  # level is the logging level: DEBUG, INFO, WARN, ERROR
  level: INFO

api:
  # base_url is the base URL to a Jellyfin instance 
  base_url: http://127.0.0.1:8096
  # token is an API token for authentication
  token: your-api-token-here
  # insecure can permit insecure SSL requests
  insecure: false
